# Generated by Django 4.2.4 on 2023-08-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_upcoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='movie/images/')),
            ],
        ),
    ]
